# config for PaBi dance

danceMotors: [5,3,6,4,8,11,10,12]
arucoIDS: [429, 260, 868, 576, 282, 754, 1007, 422, 120, 100]

motors0: [5, 3]

motors1: [6, 4]

motors2: [8, 11]

motors3: [10, 12]

motor4:
  joint: 1
  extendor: 0
  init_angle: 120

motor6:
  joint: 1
  extendor: 1
  init_angle: 120

motor5:
  joint: 0
  extendor: 1
  init_angle: 150

motor3:
  joint: 0
  extendor: 0
  init_angle: 150

motor10:
  joint: 3
  extendor: 1
  init_angle: 240

motor12:
  joint: 3
  extendor: 0
  init_angle: 240

motor8:
  joint: 2
  extendor: 1
  init_angle: 30

motor11:
  joint: 2
  extendor: 0
  init_angle: 30